#!/bin/bash -eu

. debian/debian.env

# Overide default GCC version to the default in Jammy
GCC="gcc-13"

# Override options in rules.d/hooks.mk (normally master does not have this
# file but it got added for generic annotations enforcement.
cat <<EOD >"${DEBIAN}/rules.d/hooks.mk"
do_tools_common     = false
do_tools_host       = false
do_lib_rust     = false
gcc = $GCC
rustc			= rustc-1.82
rustfmt			= /usr/lib/rust-1.82/bin/rustfmt
bindgen			= bindgen-0.65
EOD

#
# Re-enable producing linux-modules-extra for backwards compatibility.
#
echo "do_extras_package = true" >>${DEBIAN}/rules.d/amd64.mk
